name: CI

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "38"
          - "39"
          - "310"
          - "311"
          - "312"
        pytest:
          - "*"
        include:
          - python: "312"
            pytest: "3.8"
          - python: "312"
            pytest: "4"
          - python: "312"
            pytest: "5"
          - python: "312"
            pytest: "6"
          - python: "312"
            pytest: "7"
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
    - uses: cachix/cachix-action@v12
      with:
        name: devenv
    - name: Run tests
      run: |
        cat <<'EOF' >test.sh
        if [[ $PYTEST_VERSION == '*' ]]; then
          testenv=py$PYTHON_VERSION
        else
          testenv=py$PYTHON_VERSION-pytest$PYTEST_VERSION
        fi
        tox -e $testenv
        EOF
        nix develop --impure .#$PYTHON_VERSION -c bash -e test.sh
      env:
        PYTHON_VERSION: ${{ matrix.python }}
        PYTEST_VERSION: ${{ matrix.pytest }}

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
    - uses: cachix/cachix-action@v12
      with:
        name: devenv
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Run pre-commit
      run: |
        nix develop --impure . -c pre-commit run --all-files
